version: "3"
services:
  letheand:
    command:
      - import
    container_name: chain-daemon
    env_file:
      - .env
    volumes:
      - ./data:/home/lthn/chain/data
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:48782/json_rpc" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    image: "lthn/chain"

