version: "3"
services:
  letheand:
    command:
      - docker
    container_name: chain-daemon
    env_file:
      - .env
    volumes:
      - ./data:/home/lthn/chain/data
    expose:
      - "48782"
      - "48772"
    ports:
      - "48782:48782"
      - "48772:48772"
    image: "lthn/chain"
