version: "3"
services:
  letheand:
    container_name: chain-daemon
    env_file:
      - .env
    volumes:
      - "chain:/home/lthn/data/chain/lmdb"
    ports:
      - "48782:48782"
      - "48772:48772"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:48782/json_rpc" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    image: "lthn/chain"
volumes:
  chain:
