name: Alpha Build

on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  macos-intel:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: npm run build:macos-intel
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: alpha-channel
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/bin/lethean-darwin-amd64


  macos-arm64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: npm run build:macos-arm
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: alpha-channel
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/bin/lethean-darwin-arm64

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: npm install --legacy-peer-deps
      - run: cd frontend && npm install --legacy-peer-deps
      - name: Install Deno
        run: iwr https://deno.land/x/install/install.ps1 -useb | iex
      - name: Build
        run: npm run ci:windows
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: alpha-channel
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/bin/lethean.exe

