name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - release-static-linux-x86_64
          - release-static-freebsd-x86_64
          - release-static-mac-x86_64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          pull: true
          args: RELEASE_TYPE=${{ matrix.target }}
          target: build-result
          tags: lthn/chain:${{ matrix.target }}-cache
          outputs: type=local,dest=${{ github.workspace }}/lthn-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: papeloto/action-zip@v1
        with:
          files: lthn-release/ README.md LICENSE
          dest: ${{ matrix.target }}.zip
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: development
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ matrix.target }}.zip