name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build the Docker image
    
      run: docker build . --file Dockerfile --tag lthn/chain:latest
