name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NodeJS Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            frontend/node_modules
            lthn/node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodejs-
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: GoLang Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: npm install --legacy-peer-deps
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: npm run build:linux
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: development
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/bin/lethean
#      - uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest-windows"
#          prerelease: true
#          title: "Windows Portable"
#          files: |
#            LICENCE
#            build/bin/*
#


